image: registry.timmertech.nl/docker/docker:latest

stages:
  - build

variables:
  CI: "true"
  DOCKER_DRIVER: overlay2

################################################################################
# Workflow
workflow:
  rules:
    # If $VERSION variable defined have it take precedence over the commit tag
    - if: $VERSION
      variables:
        RELEASE: "${VERSION}"
    # When the CI_COMMIT_TAG is present we are override the Gradle command
    # and configuring the tag as the version to build
    - if: $CI_COMMIT_TAG
      variables:
        RELEASE: "${CI_COMMIT_TAG}"
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
      when: never
    - if: "$CI_COMMIT_BRANCH"
    - when: always

################################################################################
# Template(s)
################################################################################
.build:
  stage: build
  interruptible: true
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest
  before_script:
    - echo "${CI_DEPENDENCY_PROXY_PASSWORD}" | docker login -u "${CI_DEPENDENCY_PROXY_USER}" --password-stdin "${CI_DEPENDENCY_PROXY_SERVER}"
    - echo "${CI_JOB_TOKEN}" | docker login -u gitlab-ci-token --password-stdin ${CI_REGISTRY}
    - echo "${DOCKERHUB_PASS}" | docker login -u ${DOCKERHUB_USER} --password-stdin ${DOCKERHUB_REGISTRY}

branches:
  extends: .build
  variables:
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:${CI_COMMIT_REF_SLUG}
  only:
    - branches
  except:
    - main
  script:
    - make build push

mongo:44:
  extends: .build
  variables:
    DOCKER_FILE: Dockerfile.44
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:4.4
    DOCKER_IMAGE_HUB: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:4.4
  only:
    - main
    - schedules
  script:
    - make build-44 push
  after_script:
    - docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_HUB}
    - docker push ${DOCKER_IMAGE_HUB}

mongo:50:
  extends: .build
  variables:
    DOCKER_FILE: Dockerfile.50
    DOCKER_IMAGE: ${CI_REGISTRY}/${CI_PROJECT_PATH}:5.0
    DOCKER_IMAGE_HUB: ${DOCKERHUB_REGISTRY}/${DOCKERHUB_NAMESPACE}/${CI_PROJECT_NAME}:5.0
  only:
    - main
    - schedules
  script:
    - make build-50 push
  after_script:
    - docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_HUB}
    - docker push ${DOCKER_IMAGE_HUB}
