#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../cont-mongo.d/functions
source /etc/cont-mongo.d/functions

if [ ! -f "${MONGO_CONFIG}" ]; then
  log-init "loading default configuration"
  s6-setuidgid abc cp -r /defaults/mongo/mongod.conf "${MONGO_CONFIG}"
fi

# Unix Socket directory
if [ ! -d "${MONGO_SOCKET_DIR}" ]; then
  mkdir -p "${MONGO_SOCKET_DIR}"
fi
chown -R abc:abc "${MONGO_SOCKET_DIR}"
set_mongo_param "net.unixDomainSocket.pathPrefix" "${MONGO_SOCKET_DIR}"

# directoryPerDB
if is_enabled "${MONGO_DIRECTORY_PER_DB}"; then
  set_mongo_param "storage.directoryPerDB" true
else
  set_mongo_param "storage.directoryPerDB" false
fi

# EOF