#!/usr/bin/with-contenv bash
# shellcheck shell=bash
set -e

# shellcheck source=../cont-mongo.d/functions
source /etc/cont-mongo.d/functions

# import user crontabs
crontab -u root /config/cron/root
crontab -u abc /config/cron/abc

# EOF